type RoseItemType = "equipment" | "consumable" | "etc";

type RoseItemClassification =
  | "material"
  | "chemical"
  | "potion"
  | "magicItem"
  | "refiningMaterial"
  | "metal"
  | "otherworldlyMetal"
  | "leather"
  | "cloth"
  | "woodenMaterial"
  | "stoneMaterial";

type RoseItemGroup =
  | "junonMaterials"
  | "lunaMaterials"
  | "eldeonMaterials"
  | "consumables"
  | "refines"
  | "otherMaterials"
  | "resources";

type Item = {
  id: number;
  name: string;
  icon_id: number;
  type: RoseItemType;
  classification: RoseItemClassification;
  group: RoseItemGroup;
};

const CHEMICALS: Item[] = [
  {
    id: 12081,
    name: "Lisent (Fe)",
    icon_id: 1014,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
  {
    id: 12082,
    name: "Lisent (Cu)",
    icon_id: 1015,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
  {
    id: 12083,
    name: "Lisent (Pb)",
    icon_id: 1016,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
  {
    id: 12084,
    name: "Lisent (Al)",
    icon_id: 1017,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
  {
    id: 12085,
    name: "Lisent (Hg)",
    icon_id: 1018,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
  {
    id: 12086,
    name: "Lisent (Na)",
    icon_id: 1019,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
  {
    id: 12087,
    name: "Lisent (Cr)",
    icon_id: 1020,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
  {
    id: 12088,
    name: "Lisent (Au)",
    icon_id: 1021,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
  {
    id: 12109,
    name: "Lisent (Ag)",
    icon_id: 1532,
    type: "etc",
    classification: "chemical",
    group: "refines",
  },
];

const MAGIC_ITEMS: Item[] = [
  {
    id: 10384,
    name: "Storm Charm",
    icon_id: 1779,
    type: "consumable",
    classification: "magicItem",
    group: "consumables",
  },
];

const MATERIALS: Item[] = [
  {
    id: 12116,
    name: "Netil",
    icon_id: 1924,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12117,
    name: "Metil",
    icon_id: 1925,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12118,
    name: "Etil",
    icon_id: 1926,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12119,
    name: "Petil",
    icon_id: 1927,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12120,
    name: "Setil",
    icon_id: 1928,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12151,
    name: "Black Heart",
    icon_id: 1911,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12152,
    name: "Green Heart",
    icon_id: 1912,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12153,
    name: "Blue Heart",
    icon_id: 1913,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12154,
    name: "Pink Heart",
    icon_id: 1914,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12155,
    name: "Red Heart",
    icon_id: 1915,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12156,
    name: "Golden Heart",
    icon_id: 1916,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12157,
    name: "White Heart",
    icon_id: 1917,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12161,
    name: "Green Crystal",
    icon_id: 1963,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12162,
    name: "Blue Crystal",
    icon_id: 1964,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12163,
    name: "Red Crystal",
    icon_id: 1965,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12164,
    name: "White Crystal",
    icon_id: 1966,
    type: "etc",
    classification: "material",
    group: "otherMaterials",
  },
  {
    id: 12170,
    name: "Hook Wind Piece",
    icon_id: 5362,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
  {
    id: 12176,
    name: "Insect Leg",
    icon_id: 1974,
    type: "etc",
    classification: "material",
    group: "junonMaterials",
  },
  {
    id: 12177,
    name: "Insect Wing",
    icon_id: 1976,
    type: "etc",
    classification: "material",
    group: "junonMaterials",
  },
  {
    id: 12191,
    name: "Animal Leg Bone",
    icon_id: 1991,
    type: "etc",
    classification: "material",
    group: "junonMaterials",
  },
  {
    id: 12192,
    name: "Animal Backbone",
    icon_id: 1992,
    type: "etc",
    classification: "material",
    group: "junonMaterials",
  },
  {
    id: 12271,
    name: "Sharp Thorn",
    icon_id: 2139,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
  {
    id: 12272,
    name: "Noctilucent Leaf",
    icon_id: 2137,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
  {
    id: 12278,
    name: "Spider Web",
    icon_id: 2138,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
  {
    id: 12279,
    name: "Killer Leaf",
    icon_id: 2136,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
  {
    id: 12280,
    name: "Paper Wing Pieces",
    icon_id: 2134,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
  {
    id: 12281,
    name: "Plasma",
    icon_id: 2133,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
  {
    id: 12282,
    name: "Sikuku Costume",
    icon_id: 2140,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
  {
    id: 12999,
    name: "Mad Honey",
    icon_id: 1604,
    type: "etc",
    classification: "material",
    group: "eldeonMaterials",
  },
];

const CLOTHS: Item[] = [
  {
    id: 12051,
    name: "Tough Cloth",
    icon_id: 1820,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12052,
    name: "Cotton",
    icon_id: 1821,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12053,
    name: "Linen",
    icon_id: 1822,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12054,
    name: "Felt",
    icon_id: 1823,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12055,
    name: "Silk",
    icon_id: 1824,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12056,
    name: "Wool",
    icon_id: 1825,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12057,
    name: "Denim",
    icon_id: 1826,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12058,
    name: "Plain Weave",
    icon_id: 1827,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12059,
    name: "Twill",
    icon_id: 1828,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
  {
    id: 12060,
    name: "Lace",
    icon_id: 1829,
    type: "etc",
    classification: "cloth",
    group: "resources",
  },
];

const LEATHERS: Item[] = [
  {
    id: 12041,
    name: "Worn-out Leather",
    icon_id: 1807,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12042,
    name: "Thin Leather",
    icon_id: 1808,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12043,
    name: "Sleek Leather",
    icon_id: 1809,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12044,
    name: "Tough Leather",
    icon_id: 1810,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12045,
    name: "Tender Leather",
    icon_id: 1811,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12046,
    name: "Gorgeous Leather",
    icon_id: 1812,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12047,
    name: "Thick Leather",
    icon_id: 1813,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12048,
    name: "Hard Leather",
    icon_id: 1814,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12049,
    name: "Transparent Leather",
    icon_id: 1815,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
  {
    id: 12050,
    name: "Patterned Leather",
    icon_id: 1816,
    type: "etc",
    classification: "leather",
    group: "resources",
  },
];

const METALS: Item[] = [
  {
    id: 12001,
    name: "Rusted Iron",
    icon_id: 1755,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12002,
    name: "Tin",
    icon_id: 1756,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12003,
    name: "Copper",
    icon_id: 1757,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12004,
    name: "Bronze",
    icon_id: 1758,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12005,
    name: "Iron",
    icon_id: 1759,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12006,
    name: "Silver Iron",
    icon_id: 1760,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12007,
    name: "Steel",
    icon_id: 1761,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12008,
    name: "Chromium",
    icon_id: 1762,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12009,
    name: "Tiar",
    icon_id: 1763,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
  {
    id: 12010,
    name: "Damascus",
    icon_id: 1764,
    type: "etc",
    classification: "metal",
    group: "resources",
  },
];

const OTHERWORLDLY_METALS: Item[] = [
  {
    id: 12011,
    name: "Unprocessed Metal",
    icon_id: 1768,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12012,
    name: "Demon Metal",
    icon_id: 1769,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12013,
    name: "Wolf Steel",
    icon_id: 1770,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12014,
    name: "Molive",
    icon_id: 1771,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12015,
    name: "Mythril",
    icon_id: 1772,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12016,
    name: "Orihalcon",
    icon_id: 1773,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12017,
    name: "Adamantium",
    icon_id: 1774,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12018,
    name: "Otherworldly Metal",
    icon_id: 1775,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12019,
    name: "Philosopher Stone",
    icon_id: 1776,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
  {
    id: 12020,
    name: "Mercury",
    icon_id: 1777,
    type: "etc",
    classification: "otherworldlyMetal",
    group: "resources",
  },
];

const STONE_MATERIALS: Item[] = [
  {
    id: 12025,
    name: "Granite",
    icon_id: 1785,
    type: "etc",
    classification: "stoneMaterial",
    group: "resources",
  },
  {
    id: 12026,
    name: "Marble",
    icon_id: 1786,
    type: "etc",
    classification: "stoneMaterial",
    group: "resources",
  },
];

const WOODEN_MATERIALS: Item[] = [
  {
    id: 12031,
    name: "Twig",
    icon_id: 1794,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12032,
    name: "Maple Wood",
    icon_id: 1795,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12033,
    name: "Aromatic Wood",
    icon_id: 1796,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12034,
    name: "Oak Wood",
    icon_id: 17797,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12035,
    name: "Paulownia Wood",
    icon_id: 1798,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12036,
    name: "Pine Wood",
    icon_id: 1799,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12037,
    name: "Cinnamon Wood",
    icon_id: 1800,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12038,
    name: "Red Sandalwood",
    icon_id: 1801,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12029,
    name: "Otherworldly Wood",
    icon_id: 1802,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
  {
    id: 12030,
    name: "Sephiroth Wood",
    icon_id: 1803,
    type: "etc",
    classification: "woodenMaterial",
    group: "resources",
  },
];

const POTIONS: Item[] = [
  {
    id: 10056,
    name: "Vital Jam (+1)",
    icon_id: 5265,
    type: "consumable",
    classification: "potion",
    group: "consumables",
  },
  {
    id: 10057,
    name: "Vital Jam (+2)",
    icon_id: 5266,
    type: "consumable",
    classification: "potion",
    group: "consumables",
  },
  {
    id: 10058,
    name: "Vital Jam (+5)",
    icon_id: 5267,
    type: "consumable",
    classification: "potion",
    group: "consumables",
  },
];

const REFINES: Item[] = [
  {
    id: 12061,
    name: "Low Essence",
    icon_id: 1833,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
  {
    id: 12062,
    name: "Essence",
    icon_id: 1834,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
  {
    id: 12063,
    name: "Low Ether",
    icon_id: 1835,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
  {
    id: 12064,
    name: "Ether",
    icon_id: 1836,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
  {
    id: 12065,
    name: "High Ether",
    icon_id: 1837,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
  {
    id: 12066,
    name: "Elixir",
    icon_id: 1838,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
  {
    id: 12067,
    name: "Hime",
    icon_id: 1839,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
  {
    id: 12068,
    name: "Low Enthiric",
    icon_id: 1840,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
  {
    id: 12069,
    name: "Enthiric",
    icon_id: 1841,
    type: "etc",
    classification: "refiningMaterial",
    group: "refines",
  },
];

const GEMS: Item[] = [];
